on:
  schedule:
    # daily at 12:30 am
    - cron: '30 * * * *'
  workflow_dispatch:

name: codegen
jobs:
  discovery:
    uses: googleapis/discovery-artifact-manager/.github/workflows/list-services.yml@master
  batch:
    runs-on: ubuntu-20.04
    needs: discovery
    outputs:
      services: ${{ steps.chunk.outputs.result }}
    steps:
      - uses: actions/github-script@v5
        id: chunk
        with:
          script: |
            console.log('splitting service names list into batches')
            const services = ${{ needs.discovery.outputs.services }}
            const hour = new Date().getHours()
            const MAX_BATCH_SIZE = 100
            const result = {
              batches: [],
              hour: new Date().getHours(),
            };
            for (let i = 0; i < services.length; i += MAX_BATCH_SIZE) {
              result.batches.push(services.slice(i, i + MAX_BATCH_SIZE))
            }
            return result
  generate:
    uses: googleapis/google-api-java-client-services/.github/workflows/generate.yaml@matrix-fix-2
    needs: batch
    if: ${{!!fromJson(needs.batch.outputs.services).batches[fromJson(needs.batch.outputs.services).hour]}}
    with: 
      # services: ${{fromJson(needs.batch.outputs.services).batches[fromJson(needs.batch.outputs.services).hour]}}
      services: ${{fromJson(needs.batch.outputs.services).batches[0]}}