on:
  schedule:
    # daily at 12:30 am
    - cron: '30 0,1 * * *'
  workflow_dispatch:

name: codegen
jobs:
  discovery:
    uses: googleapis/discovery-artifact-manager/.github/workflows/list-services.yml@master
  batch:
    runs-on: ubuntu-20.04
    needs: discovery
    outputs:
      services: ${{ steps.chunk.outputs.result }}
    steps:
      - uses: actions/github-script@v5
        id: chunk
        with:
          script: |
            console.log('splitting service names list into batches')
            const services = ${{ needs.discovery.outputs.services }}
            const hour = new Date().getHours()
            const result = {
              "one": [],
              "two": [],
              "isEvenHour": hour % 2 == 0,
            };
            for (let i = 0; i < services.length; i++) {
              resultBatchKey = i % 2 ? "one" : "two";
              result[resultBatchKey].push(services[i])
            }
            return result
  generate_one:
    runs-on: ubuntu-20.04
    needs: batch
    if: ${{fromJson(needs.batch.outputs.services).isEvenHour}}
    steps:
      - uses: googleapis/google-api-java-client-services/generate.yaml@matrix-fix-2
        with: 
          services: fromJson(needs.batch.outputs.services).one
  generate_two:
    runs-on: ubuntu-20.04
    needs: batch
    if: ${{!fromJson(needs.batch.outputs.services).isEvenHour}}
    steps:
      - uses: googleapis/google-api-java-client-services/generate.yaml@matrix-fix-2
        with: 
          services: fromJson(needs.batch.outputs.services).two